version: "3.7"

services:
  foundry:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/usr/src/app
    ports:
      - 5001:5000
    environment:
      - FLASK_APP=render/__init__.py
      - FLASK_ENV=development
      - APP_SETTINGS=render.config.DevelopmentConfig
